version: '3.8'
services:
  mariadb-container:
    image: mariadb
    environment:
    - MARIADB_ROOT_PASSWORD=root
  wordpress-container:
    image: wordpress
    ports:
    - "8080:80"
    depends_on:
    - mariadb-container